### ISSUE TITLE
設計をしましょう

### ISSUE THREAD

**Issue by haruki201355** [SectionOf2/Liam_repository#2]
厳しいことを言いますが、作成したプログラムは、素人の入門レベルです。
初めから作成する気持ちでやり直しましょう。

https://github.com/orgs/SectionOf2/teams/01_c/discussions/1
上記を参考に、まずは設計から始めます。

ここでよいので、やりたいことを箇条書きで列挙し、要件を定義しましょう。

**Comment by LiamHTomomizu** [comment]
マルバツゲームのやりたいこと
・縦３×横３のマルバツゲーム
・先手が◯、後手が×
・先手(◯)と後手(×)が順番にユーザーが手入力できる
・１〜９の数字が入力をさせ、それ以外はもう一度入力
・既に、１〜９の数字が入力されている場合は、もう一度入力
・◯か×どちらからが縦・横・斜めの一列を先取した方の勝ち
・勝利した時、勝利した側を表示する
・勝敗が決まらず、９マスすべて埋まった段階で引き分け
・ゲーム終了後、タイトル画面に戻ること
・マルバツゲームのタイトル画面を作成。1でゲームスタート、２でゲームを終了。

**Comment by haruki201355** [comment]
わかりました。

>・ゲーム終了後、タイトル画面に戻ること

これについてもう少し詳細を教えてください。
イメージを書いてもいいです。

**Comment by haruki201355** [comment]
それから、
品質特性モデルを考慮した場合、今回自分が作成したコードに対して、
問題があるとしたらどのへんか、思いつく限り列挙してください。

**Comment by LiamHTomomizu** [comment]
品質特性モデルを考慮した、自作プログラムの問題点
機能性[3点]
・一つの要件を除き、要件を満たせている
　(「ゲーム終了後、タイトル画面に戻り、ゲームを再開できること」という要件が漏れていました)

信頼性[5点]
・マルバツゲームをバグなく、正常にプレイできる。

使用性[5点]
・簡単に使用・理解できる(マルバツゲーム自体が単純なため)

効率性[2点]
・単純でバグのないプログラムを重視して作成したため、効率的に作成できているか不明
　while文でループさせているため、無駄に一周回っているので、if文で作成した方が効率的だったのではないかと思います。
　(私が効率的なプログラムがどのようなものか理解できていない)

保守性[1点]
・コーディング規約を徹底して守れていないので、改修する際に問題になると思う
　(今見直したところ、if文の後にelseが不足している)

移植性[0点]
・考慮して作成していないため、別の環境になった際、動くか不明です。

**Comment by haruki201355** [comment]
@LiamHTomomizu 

サンキュー。自己評価としてはいいでしょう。
せっかくなので、私からの評価も書いておきます。

---
**機能性[2点]**
- うん、要件を満たせていないね。
- あまり多くない要件の中で、かつ明らかにユーザー目線ですぐ気づく要件を満たせていないのはマイナスだね。

**信頼性[2点]**
- え！バグあるよ。
  - 最初の時点で気づいていたけど黙っててごめんね。
  - スタート→1→2→1→。。。

**使用性[3点]**
- ただコード量が少ないってだけで、これを簡単に理解できるコードとは言えないかな。
- 逆に、同じようなコードが出てくるのは問題だね。
  - 先攻の処理と後攻の処理ってなんだか一緒だよね。

**効率性[4点]**
- この程度のプログラムでは、効率性を議論するところはないね。
- よっぽど無駄が無いコードを欠かない限り、ここは問題にならないと思います。

**保守性[1点]**
- そうだね。ここをもう少し意識してほしいです。
- コーディング規約もそうだけど、機能ごとに独立性を持たして、改良や追加などをしやすくすることを意識したいね。

**移植性[1点]**
- 移植をどのように捉えるかで評価は変わってきますが、
- 例えば今回、入出力をCUIだけど、今後GUIに載せ替えたときに、ここの機能はこのまま流用できる。とか
- 機能追加をしやすく、追加要素のある機能は独立させる。とか

**総評**
- プログラミングの勉強のためのコードなので、main関数1つですべてを実装するのは、問題外です。
- 機能とは何か、関数とは何か、保守性や移植性を意識して、機能性を満たすとはどの様なことかを、勉強していく必要があります。
- 同じようなコードが2つ以上出てくるのも、同じ原因です。
- いきなりすべてを理解して、完璧なコードを作ることも不可能なので、少しずつ覚えていきましょう。
---

っと、色々書きましたが、この品質特性モデルは、コードを書く上で、必ず守るルールというわけではありません。そして、厳密性もないため、人の見方によって、評価や考え方も変わってきます。
では、なんであるかというと、
### **良いソフトウェアを書くためにはどうすればいいのか。**
これを考えるための1つの指標です。

よって、どの様なコードを書くと良いコードなのか、目的を持って書くことが重要になります。
もちろん、 _1つの関数で全てを書くことをアピールする！_ ことが目的なのであれば、あなたのコードは悪くありません。

まあ、これから勉強して行きましょう。

**Comment by haruki201355** [comment]
さて、話を戻して、これからの話しをしましょう。
わかっていると思いますが、1から作りながら勉強して行きましょう。
ただ、同じものを作っては面白くないので、私から要件を出します。

---
# 要求仕様：レジェンドステージへの機能拡張を考慮した、ミドルステージの○☓ゲームの作成
* 仕様は、[営業所の仕様](https://sites.google.com/a/systena.co.jp/nagoya2/ji-shu-li-xiang-shang-tui-jin-wei-yuan-hui/purokon/di1hui)のままでよいです。
* 拡張性や移植性を考慮して、各機能の独立性を意識して作りましょう。
  * AI機能を作って欲しいわけではありません。

以上。
---

さて、早速実装に移りたいところですが、やはりある程度の設計から始めましょう。
ただし、ガチガチに設計するわけではなく、アジャイル的に作っていきましょう。

まずは、最初にもやったように、上記、要求仕様に対して実現するための要件定義をしましょう。
書き方としては、仕様から抽出した、実現すべき機能を列挙していきましょう。
例）
* コンソールから文字を入力することができる。
* メニューを表示することができる。
* 勝敗を決めることができる。
等々。
まずは、まとまっていなくてもいいので、書けるだけ書き出してください。

**Comment by haruki201355** [comment]
あ、要求仕様に対する質問は受付ますよ。
QAの重要性については、、、もういいですよね。

**Comment by LiamHTomomizu** [comment]
アップが遅くなり申し訳ございません。
要件定義をいたしましたので、確認をお願いいたします。

要件定義
・コンソール画面から文字入力ができる。
・ゲーム進行中は、３×３の画面を入力できる。
・「１」～「９」までの数値の入力を促し、入力された数値のマスを手番側の記号（先手なら○）で埋めることができる。
・タイトル画面を表示することができる。
・タイトル画面では、対人モードと・CPUモード・終了を数字で選択できる。
　(対人モード：１、対CPUモード：２、終了：３)
・勝敗を決めることができる。(勝敗決定画面を表示できる)
・勝敗決定後、次の手番を実行せずに勝敗決定画面を表示することができる。
・勝敗決定後、勝ち負け引き分けの３パターンの勝敗決定画面を表示できる。
・勝敗がつかなくても、９マス埋まった時点で、引き分け表示ができる。
・すでに、◯・×が埋まっているところには、入力できず、再入力を促すこと
・対CPUモードでCPU側の手番になったら、自動でマスを選択し埋めること
・対CPUモードでは、先手、後手がランダムに設定されること
・対人モードでは、先手が◯、後手が×で交互に入力できる。
・レジェンドに移行できるように実装すること。

**Comment by haruki201355** [comment]
いいでしょう。それでは次に行きましょう。

何を実装するかを決めましょう。
上記要件を満たすために必要な機能をリストアップしていってください。
フォーマットは以下の感じで。

```
**＜XX機能＞**
* XXXXをする
* YYYYをする

**＜ZZ機能＞**
* ZZZZをする
```

とりあえず、思いつく限りでよいです。この辺は今後変更は可能とします。
では、よろしく。

**Comment by LiamHTomomizu** [comment]
**＜メニュー画面機能＞**
*対人モード(1)・対CPUモード(2)・終了(9)を数字で選択する
* 

**＜対人モード機能＞**
*先手◯と後手×で、ユーザ入力により交互にマルバツゲームする


**＜対CPUモード機能＞**
*CPUとマルバツゲームをする
*

**＜対戦結果表示機能＞**
*対人モード・対CPUモードの結果を表示する
*

**Comment by haruki201355** [comment]
サンキュー
少し質問をさせてください。

> ・勝敗を決めることができる。

この要件はどの機能で満たす予定ですか？
素直に答えてくれれば良いです。

**Comment by LiamHTomomizu** [comment]
対人モード・対CPUモードで、勝敗の結果まで出そうと考えておりました。
対戦結果表示機能は、下記の要件を満たすために機能として作成しました。
・勝敗を決めることができる。(勝敗決定画面を表示できる)

**Comment by haruki201355** [comment]
なるほど。わかりました。
方向性はそんなに間違っていないとは思います。

ただ、要望として、以下の点を取り込んでみてください。

* 対人モード機能 → 対人機能、対CPUモード機能 → 対CPU機能
  * 機能名にモードを入れると、機能自体が大きくなってしまう気がします。
  * 機能はなるべく小さく、独立出来るものが良いです。
* メイン機能を追加してください。
  * 個々の機能を小さく作成し、それらを制御する機能としてメイン機能を追加してほしいです。
  * メイン機能は他の機能をすべて使うイメージですが、メイン機能以外は、自分の機能を実現するのみで、他の機能を使用しません。

ちょっと、これで再度考えてみてください。
新しいコメントとして書いてもらえればよいです。

**Comment by LiamHTomomizu** [comment]
春木さんからのアドバイスを考慮し、新たに機能を追加しました。
＞機能名にモードを入れると、機能自体が大きくなってしまう気がします。
　＜領域判定・書き込み機能＞この機能を追加することによって最大限、二つのモードの処理を軽くすることができると考えています。
正直な考えですが、この要望に対して、＜領域判定・書き込み機能＞を追加しましたが、入力する都度、関数callをしなければならないため、効率の良いプログラムかどうかわかりません。
確認をお願いいたします。

〜〜以下、機能となります。〜〜
＜メイン機能＞new
*全ての機能を呼び出し、要件を満たしたマルバツゲームを実現する

＜メニュー画面機能＞
*対人モード(1)・対CPUモード(2)・終了(9)を数字で選択する
*

＜対人モード機能＞
*先手◯と後手×で、ユーザ入力により交互にマルバツゲームする

＜対CPUモード機能＞
*CPUとマルバツゲームをする
*

＜領域判定・書き込み機能＞new
*すでに、◯・×が埋まっているところには、入力できず、再入力を促すという判定を＜対人モード機能＞＜対CPUモード機能＞に渡す
*対CPUモードでCPU側の手番になったら、自動でマスを選択し埋めて、＜対CPUモード機能＞に結果を渡す。
*

＜対戦結果表示機能＞
*対人モード・対CPUモードの結果を表示する
*

**Comment by haruki201355** [comment]
うん、まあいいでしょう。
都合が悪くなったらその都度修正しましょう。

では、最後にアプリ名と機能名を命名してください。
もちろん英語表記です。

アプリ名：XXX
機能
* メイン機能：main
* メニュー画面機能：xxx
* 対人モード機能：xxx
* 対CPUモード機能：xxx
* 領域判定・書き込み機能：xxx
* 対戦結果表示機能：xxx

**Comment by LiamHTomomizu** [comment]
アプリ名：MARUBATUGAME
機能

メイン機能：main
メニュー画面機能：menu
対人モード機能：interpersonalMode
対CPUモード機能：ComputerMode
領域判定・書き込み機能：decisionReadWrite
対戦結果表示機能：resultDisplay

**Comment by haruki201355** [comment]
※先頭の大文字小文字は揃えましょう。

以上で、設計はいったん終了で、実装編に移りましょう。
